import math,string,itertools,fractions,heapq,collections,re,array,bisect,random

class TwoWaysSorting:
    def sortingMethod(self, stringList):
        s = stringList
        clen,clex = True,True
        for i in range(len(stringList) - 1):
            if not (len(s[i]) < len(s[i+1])):
                clen = False
            if not (s[i] < s[i+1]):
                clex = False
            if not clen and not clex:
                return "none"

        if clen and clex:
            return "both"
        if clen:
            return "lengths"
        return "lexicographically"

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pf 2.3.0
import sys
import time
def KawigiEdit_RunTest(testNum, p0, hasAnswer, p1):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("{"))
	for i in range(len(p0)):
		if (i > 0):
			sys.stdout.write(str(","))

		sys.stdout.write(str("\"") + str(p0[i]) + str("\""))

	sys.stdout.write(str("}"))
	print(str("]"))
	obj = TwoWaysSorting()
	startTime = time.clock()
	answer = obj.sortingMethod(p0)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		print(str("Desired answer:"))
		print(str("\t") + str("\"") + str(p1) + str("\""))

	print(str("Your answer:"))
	print(str("\t") + str("\"") + str(answer) + str("\""))
	if (hasAnswer):
		res = answer == p1

	if (not res):
		print(str("DOESN'T MATCH!!!!"))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))

	print(str(""))
	return res

all_right = True
tests_disabled = False


# ----- test 0 -----
disabled = False
p0 = ("a","aa","bbb")
p1 = "both"
all_right = (disabled or KawigiEdit_RunTest(0, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 1 -----
disabled = False
p0 = ("c","bb","aaa")
p1 = "lengths"
all_right = (disabled or KawigiEdit_RunTest(1, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 2 -----
disabled = False
p0 = ("etdfgfh","aio")
p1 = "none"
all_right = (disabled or KawigiEdit_RunTest(2, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 3 -----
disabled = False
p0 = ("aaa","z")
p1 = "lexicographically"
all_right = (disabled or KawigiEdit_RunTest(3, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 4 -----
disabled = False
p0 = ("z",)
p1 = "both"
all_right = (disabled or KawigiEdit_RunTest(4, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 5 -----
disabled = False
p0 = ("abcdef","bcdef","cdef","def","ef","f","topcoder")
p1 = "lexicographically"
all_right = (disabled or KawigiEdit_RunTest(5, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

if (all_right):
	if (tests_disabled):
		print(str("You're a stud (but some test cases were disabled)!"))
	else:
		print(str("You're a stud (at least on given cases)!"))

else:
	print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
#
# 	Sasha has a tuple (string) stringList. No two elements of stringList have the same length.
#
#
#
# 	So far, Sasha has learned two ways of sorting strings:
#
#
#
# 		He can sort strings lexicographically. For example, "car" < "carriage" < "cats" < "doggies". (See Notes for a definition of the lexicographic order.)
#
#
# 		He can also sort strings according to their lengths in ascending order. For example, "car" < "cats" < "doggies" < "carriage".
#
#
#
# 	Sasha now wonders whether stringList is sorted in either of these two ways. Return "lexicographically" (quotes for clarity) if stringList is sorted lexicographically but not according to the string lengths. Return "lengths" if stringList is sorted according to the string lengths but not lexicographically. Return "both" if it is sorted in both ways. Otherwise, return "none".
#
#
#
# DEFINITION
# Class:TwoWaysSorting
# Method:sortingMethod
# Parameters:tuple (string)
# Returns:string
# Method signature:def sortingMethod(self, stringList):
#
#
# NOTES
# -String A is lexicographically smaller than string B if A contains a character with a smaller ASCII value in the first position where they differ. In case one of the strings ends before they have a different character, the shorter one is considered smaller.
#
#
# CONSTRAINTS
# -stringList will contain between 1 and 50 elements, inclusive.
# -Each element of stringList will contain between 1 and 50 characters, inclusive.
# -Each character of each element of stringList will be a lowercase English letter ('a'-'z').
# -Every two elements of stringList will have different lengths.
#
#
# EXAMPLES
#
# 0)
# {"a", "aa", "bbb"}
#
# Returns: "both"
#
# These strings are sorted both lexicographically and according to their lengths.
#
# 1)
# {"c", "bb", "aaa"}
#
# Returns: "lengths"
#
# The lengths of these strings are in ascending order. However, they are not sorted lexicographically as, for instance, "aaa" is lexicographically smaller than "c".
#
# 2)
# {"etdfgfh", "aio"}
#
# Returns: "none"
#
# Here the first string is longer than the second one, so they are not sorted according to length. (Note that we require the lengths to be in ascending order.) Similarly, they are not sorted lexicographically: "aio" should come before "etdfgfh".
#
# 3)
# {"aaa", "z"}
#
# Returns: "lexicographically"
#
# The input strings are sorted lexicographically only.
#
# 4)
# {"z"}
#
# Returns: "both"
#
#
#
# 5)
# {"abcdef", "bcdef", "cdef", "def", "ef", "f", "topcoder"}
#
# Returns: "lexicographically"
#
#
#
# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pf 2.3.0!
